Update aws log4j2
serverless/serverless pull request #10383
Opened 2021-12-16 20:37 UTC by MarinaMeza

Updated aws-lambda-java-log4j2 to 1.4.0 to address log4j vulnerability

[Issue 10370](https://github.com/serverless/serverless/issues/10370)

Addresses: #10370

2021-12-16 21:08 UTC, pgrzesik commented
Thanks a lot @MarinaMeza 🙇 I've run a quick grep over the repo and it seems like there are some additional templates that use this package that could also use an upgrade:
- `aws-scala-sbt`
- `aws-kotlin-jvm-gradle-kts`
- `aws-kotlin-jvm-maven`
- `aws-java-maven`
- `aws-java-gradle`

Would you be interested in upgrading them too? It would be much appreciated to cover all of them as a single commit with an upgrade.

2021-12-16 21:18 UTC, MarinaMeza commented
@pgrzesik Yes, no problem! I'll upgrade those too

2021-12-17 15:48 UTC, anwari666 commented
Hi @MarinaMeza, thanks for updating those. 

I am having the same issue at my company and saw that this file https://github.com/serverless/serverless/blob/7bf8f1b723cc4f6624df7be3d27f246b3a826140/lib/plugins/aws/invokeLocal/runtimeWrappers/java/pom.xml#L25 has indirect reference to log4j. 

I'm not sure how it will impact the repo, but if it's a simple update then perhaps it can be updated within this commit as well?
Thanks!

2021-12-21 13:33 UTC, pgrzesik commented on lib/plugins/create/templates/aws-java-maven/pom.xml
> -      <version>1.1.0</version>
We should update to `1.5.0`

2021-12-21 13:33 UTC, pgrzesik commented on lib/plugins/create/templates/aws-kotlin-jvm-maven/pom.xml
> +            <version>1.4.0</version>
same here

2021-12-21 14:48 UTC, MarinaMeza commented
I've updated all references to aws-lambda-java-log4j2. 
I left aws-lambda-java-log4j as it was since i could not find a newer version

2021-12-21 15:15 UTC, pgrzesik requested changes
Thank you @MarinaMeza, it looks great, but there seem to be a conflict - could you rebase your branch on top of current `master` branch?

2021-12-27 10:33 UTC, pgrzesik approved these changes
Thank you @MarinaMeza 🙇

2021-12-27 10:34 UTC, merged