Adding force deploy flag to s3 event trigger
serverless/serverless pull request #11066
Opened 2022-05-12 09:07 UTC by simonarcher99

I have added a forceDeploy flag to the s3 bucket event trigger. The same logic has been used as in [#10435](https://github.com/serverless/serverless/pull/10435).

Closes: [issue 10939](https://github.com/serverless/serverless/issues/10939)

2022-05-12 10:49 UTC, JamesWelshKaluza approved these changes
Great work!

2022-05-12 15:49 UTC, pgrzesik requested changes
It looks good in general 👍 I only have a few minor comments - after addressing them we should be good to go 👍

2022-05-12 15:49 UTC, pgrzesik commented on docs/providers/aws/guide/serverless.yml.md
> +          # Optional, for forcing deployment of triggers on existing User Pools
Let's make sure it does not reference User Pools in the comment - I believe it's a copy/paste comment that wasn't adjusted

2022-05-12 15:49 UTC, pgrzesik commented on lib/plugins/aws/package/compile/events/s3/index.js
> +                    ForceDeploy: forceDeployProperty,
Let's add that property only if it's actually defined - that will allow us to avoid the unnecessary `ForceDeploy: undefined` in tests

2022-05-12 18:36 UTC, simonarcher99 commented
Thanks for the comments I think these should both be addressed now

2022-05-12 22:39 UTC, Hibanka requested changes

2022-05-12 22:39 UTC, Hibanka commented on package.json
> +    "test:isolated": "mocha-isolated \"test/unit/lib/plugins/aws/package/compile/events/s3/index.test.js\""
```suggestion
    "test:isolated": "mocha-isolated \"test/unit/**/*.test.js\""
```

2022-05-13 06:56 UTC, pgrzesik approved these changes
Thanks @simonarcher99 - that looks good 👍

2022-05-13 06:57 UTC, merged

2022-05-19 14:32 UTC, simoncpu commented
Hehe... I was wondering why I'm getting the error "unrecognized property 'forceDeploy'". Turns out that this is a new feature. :)

2022-05-19 14:55 UTC, pgrzesik commented
Hey @simoncpu - sorry about that! I will be released either later today or tomorrow with new Framework version 👍