Addressing-7747;-_.merge-=>-Object.assign
serverless/serverless pull request #11267
Opened 2022-07-22 08:19 UTC by pjmattingly

Closes: #7747

2022-07-22 08:25 UTC, pjmattingly commented
some _.merge instance can't be replaced with Object.assgn; Those files are:

```
/lib/classes/service.js
    /lib/plugins/aws/package/compile/events/cloud-front.js
    /lib/plugins/aws/package/compile/events/cognito-user-pool.js
    /lib/plugins/aws/package/compile/events/alb/lib/permissions.js
    /lib/plugins/aws/package/compile/events/api-gateway/lib/usage-plan.js
    /lib/plugins/aws/package/compile/events/api-gateway/lib/method/index.js
    /lib/plugins/aws/package/lib/merge-custom-provider-resources.js
```

Some files had no tests, and so were not modifed; Those files are:

```
/lib/plugins/aws/package/compile/events/api-gateway/lib/method/responses.js
    /lib/plugins/aws/package/compile/events/websockets/lib/api.js
    /test/utils/api-gateway.js
```

Some test files use _.merge, so those were skipped as they weren't in customer-facing code:

```
/test/unit/lib/configuration/variables/sources/instance-dependent/get-aws.test.js
    /test/unit/lib/configuration/variables/sources/instance-dependent/get-sls.test.js
```

2022-07-22 11:12 UTC, pgrzesik requested changes
Thanks a lot @pjmattingly - it looks good in general! I have a few comments, please let me know what do you think 🙇

2022-07-22 11:12 UTC, pgrzesik commented on lib/classes/config.js
> +    return Object.assign(this, config);
Did you validate that it's going to be a safe change? It seems like a pretty generic method where deep vs shallow copy behavior might have an impact

2022-07-22 11:12 UTC, pgrzesik commented on lib/classes/service.js
> +    return Object.assign(this, data);
Is it safe to use `Object.assign` here? Is the deep merge not needed here?

2022-07-22 11:12 UTC, pgrzesik commented on lib/classes/service.js
> +    this.pluginsData = Object.assign(this.pluginsData, data);
Is it safe to use `Object.assign` here? Is the deep merge not needed here?

2022-07-22 11:12 UTC, pgrzesik commented on lib/plugins/aws/package/compile/events/cloud-front.js
> +      // #7747, could not replace _.merge with Object.assign, as this does deep merges
I think these assignments look pretty safe to be refactored - do you think we should keep merge here?

2022-07-25 14:41 UTC, medikoo reviewed
@pgrzesik @pjmattingly with this change (while it's highly desirable) we need to be very careful. 

If we touch not well tested areas it's possible we may introduce regressions, as behavior of `_.merge` and `Object.assign` differs.

Ideally, if each change is validated individually by looking through carefully what it does and what further logic it affects.

I would also add a comment in each case where we leave `_.merge` usage with reasoning, on why `_.merge` is wanted approach

@pjmattingly please confirm also by running integration tests, that we did not break anything

2022-07-25 20:57 UTC, pjmattingly commented
@medikoo 
> please confirm also by running integration tests, that we did not break anything

Will do.

> I would also add a comment in each case where we leave _.merge usage with reasoning, on why _.merge is wanted approach

I'll find my notes and add some more detail in comments for the unchanged ones.

> Ideally, if each change is validated individually by looking through carefully what it does and what further logic it affects.

I was working on #11273 and I found a need for inspecting objects during testing (See also: https://www.reddit.com/r/javascript/comments/w7ial4/askjs_a_library_for_tracking_the_properties_of_an/?). I think such functionality might also be helpful here, as the properties for the object can be tracked during (integration) testing. Would you agree?

If so, then it might be worth making / finding code to track and report on the different values that effected objects go through and potentially where the code is called from. This way we can have more confidence about: 1) What properties and values the objects typically take and 2) What external code these changes touch.

What do you think?

2022-07-26 07:43 UTC, medikoo commented
> If so, then it might be worth making / finding code to track and report on the different values that effected objects go through and potentially where the code is called from. 

I'm not sure if it's necessary to bundle such a thing into a test suite. It feels a bit overkill (and definitely adds to technical debt), but if in this specific case, it would help you test whether change is not breaking. Feel free to  set up such thing temporarily (just to test proposed changes, but not be a part of a PR)

2022-07-26 08:28 UTC, pjmattingly commented
Exactly. Thanks for weighing in!

On Tue, Jul 26, 2022 at 1:43 AM Mariusz Nowak ***@***.***>
wrote:

> If so, then it might be worth making / finding code to track and report on
> the different values that effected objects go through and potentially where
> the code is called from.
>
> I'm not sure if it's necessary to bundle such a thing into a test suite.
> It feels a bit overkill (and definitely adds to technical debt), but if in
> this specific case, it would help you test whether change is not breaking.
> Feel free to set up such thing temporarily (just to test proposed changes,
> but not be a part of a PR)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/serverless/serverless/pull/11267#issuecomment-1195125111>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABP7MZ7HYF4H7TIH24HDBK3VV6JLFANCNFSM54KPBF2Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-28 13:38 UTC, pjmattingly commented
Integration tests look good.

Next, adding notes about why leaving in some `_.merge()`s. Then, getting a closer look at each change to determine the inputs and outputs, and what other code is effected by these changes indirectly.

> I would also add a comment in each case where we leave _.merge usage with reasoning, on why _.merge is wanted approach

> Ideally, if each change is validated individually by looking through carefully what it does and what further logic it affects.

2022-07-28 15:44 UTC, medikoo commented
@pjmattingly once it's ready for re-review, it's best if you simply re-request review in right top box

2022-07-29 04:30 UTC, pjmattingly commented
Okay, will do. I as making notes to show progress toward completion; It helps me remember what I was doing with this PR.

Is that okay?

2022-07-29 08:24 UTC, medikoo commented
> Okay, will do. I as making notes to show progress toward completion; It helps me remember what I was doing with this PR.
> Is that okay?

Yes, that's totally good. Great thanks for helping on that one 👍

2023-03-07 03:32 UTC, closed without merging