fix(AWS Lambda): add logs:TagResource permission to AWS Lambda IAM role
serverless/serverless pull request #11766
Opened 2023-02-27 12:42 UTC by mgerlach

As announced by AWS in Dec 2022, there is a new API for tagging CloudWatch resources. New accounts/roles that need to tag CloudWatch LogGroups need the new logs:TagResouce permission.

Closes: #11762

2023-02-27 13:25 UTC, medikoo requested changes
@mgerlach great thanks for that PR!

It all looks good, apart of styling, which should match Prettier formatting (please see CI fail). Can you fix that?

2023-02-27 16:55 UTC, mgerlach commented
@

> @mgerlach great thanks for that PR!
> 
> It all looks good, apart of styling, which should match Prettier formatting (please see CI fail). Can you fix that?

@medikoo done, can you approve so the checks can run?

Would this automatically trigger a patch release?

2023-02-28 08:24 UTC, medikoo approved these changes
Thank you @mgerlach 👍

2023-02-28 08:25 UTC, merged

2023-02-28 08:36 UTC, mgerlach commented
@medikoo np... any hint when this change will be released?