Avoid lambda permission for log subscriptions from depending on itself
serverless/serverless pull request #11864
Opened 2023-03-27 20:20 UTC by mjdickinson

I just filtered the resources's own logical ID from the list of dependencies in the lambda permission template.

2023-03-28 15:20 UTC, medikoo requested changes
Thank you @mjdickinson !

It looks as regression introduced by https://github.com/serverless/serverless/pull/11788 (cc @rnielsen )

Can you add a regression test for it?

2023-03-28 17:50 UTC, mjdickinson commented
Tests added.

2023-03-29 06:56 UTC, medikoo requested changes
Thank you @mjdickinson , it looks great, just tests needs to be configured with different method. Let me know if you have any further questions on that, I'll do my best to help

Also after PR is ready for re-review simply re-request review in reviewers box

2023-03-29 06:56 UTC, medikoo commented on test/unit/lib/plugins/aws/package/compile/events/cloud-watch-log.test.js
> +      expect(
New tests should be configured via `runServerless` util, as e.g. tests in this block: https://github.com/serverless/serverless/blob/5d1c3f7ed4d481619d412b6b453d6eaf94b32b4a/test/unit/lib/plugins/aws/package/compile/events/websockets/index.test.js#L116-L258

See also: https://github.com/serverless/serverless/tree/main/test#unit-tests

In this test file let's add a new `describe` block, that will host those new tests

2023-04-01 05:54 UTC, mjdickinson commented
I don't have time to refactor the existing tests.  This PR is an emergency bug with regression tests added, as requested.  Personally, I'm not blocked - I have a workaround.  Please feel free to close the PR.

2023-04-03 10:52 UTC, closed without merging