Refactor `plugin-manager.test.js`
serverless/serverless pull request #11861
Opened 2023-03-25 03:44 UTC by sleepwithcoffee

#8603

This is a follow up of PR https://github.com/serverless/serverless/pull/11853
Under this PR, I refactor `plugin-manager.test.js` to conform with several common code conventions
* remove `.bind(this)` if arrow function is already sufficient
* Use `to.eventually.be.rejectedWith` instead of `to.be.rejectedWith`, more verbose but screams out promise
* Use `to.eventually.be.fulfilled` instead of `to.not.be.rejected`
* Favor `await` over promises, unless it is a one-line return statement (best practice is always using `await` within function brackets)

2023-03-25 03:46 UTC, sleepwithcoffee commented
weird failed test. I tried to run in my local

`npx mocha test/unit/lib/configuration/resolve-provider-name.test.js`
```
  test/unit/lib/configuration/resolve-provider-name.test.js
    ✔ should read name from "provider"
    ✔ should read name from "provider.name"
    ✔ should reject missing "provider.name"
    ✔ should reject invalid "provider.name"
    ✔ should reject missing "provider"


  5 passing (13ms)
```

`node --version` (also tested with  node v12, v14 and v16)
```
v16.19.1
```

2023-03-25 05:30 UTC, sleepwithcoffee commented
reverted the troubled piece of code

![image](https://user-images.githubusercontent.com/3896985/227698308-79329eaf-b3f3-42af-9b65-550e3d9bb1ef.png)

2023-03-27 10:17 UTC, medikoo requested changes
@sleepwithcoffee great thanks for the effort, still let's not adjust the old tests like that.

If we're about to do any work of them, they should be refactored to `runServerless` usage, See https://github.com/serverless/serverless/tree/main/test#unit-tests

2023-03-27 10:17 UTC, medikoo commented on test/unit/lib/classes/plugin-manager.test.js
> +      expect(pluginManager.cliOptions).to.be.an('object').empty;
Let's leave original form `to.deep.equal({})` is totally acceptable.

Same in below cases

2023-03-27 10:17 UTC, medikoo commented on test/unit/lib/classes/plugin-manager.test.js
> +      expect(pluginManager.cliCommands).to.deep.equal(commands);
Let's nott change this test.

In general those old tests, if refactored, they should rather be refactored to `runServerless` usage (see https://github.com/serverless/serverless/tree/main/test#unit-tests). We should not invest time into further mainainace of old tests (unless it helps us in some way, as e.g. getting rid of some dependency)

2023-03-27 12:41 UTC, sleepwithcoffee commented
hi @medikoo these are only meant to be syntactical changes, I do not intend to change the way they work (yet).

2023-03-27 14:02 UTC, sleepwithcoffee commented
sure, maybe let me scope down this PR a bit. Some of them are still quite meaningful including highlighting async functions that we might have missed out earlier.
Another meaningful change is to remove `sinon-chai` by using built-in alternative in `chai` alone.

2023-03-27 14:05 UTC, medikoo commented
> sure, maybe let me scope down this PR a bit. Some of them are still quite meaningful including highlighting async functions that we might have missed out earlier.
Another meaningful change is to remove sinon-chai by using built-in alternative in chai alone.

@sleepwithcoffee you're doing great work here. What's important in case of old tests (those not configured with `runServerlss`), they're scheduled to be removed in favor of `runServerless` counterparts. So it makes not much sense to work on improvements to those, as it'll anyway be deleted.

Best improvement would be to simply replace them with `runServerless`  based variants as we did in many other files already. Such contribution is very highly welcome.

2023-03-27 15:39 UTC, medikoo commented on test/unit/lib/classes/plugin-manager.test.js
> +      expect(plugin1.asyncInit.calledOnce).to.be.true;
Let's not introce such stylistic changes (`to.equal(true)` into `to.be.true`), it brings on extra value, while increases maintenance cost

2023-03-30 13:16 UTC, sleepwithcoffee commented
I am closing this PR

2023-03-30 13:16 UTC, closed without merging