Refactor to remove Promise.bind()
serverless/serverless pull request #11875
Opened 2023-03-30 13:12 UTC by sleepwithcoffee

Addresses: #8369

2023-03-30 13:48 UTC, medikoo requested changes
Thank you @sleepwithcoffee, it looks very good. I have just one improvement suggestion

2023-03-30 13:48 UTC, medikoo commented on lib/plugins/plugin/search.js
> +    return Promise.resolve(this)
Same here

2023-03-30 13:51 UTC, sleepwithcoffee commented on lib/plugins/plugin/list.js
> +    return Promise.resolve(this)
We still need that to pass `this` context to the following functions, either that or:

```
return this.getPlugins()
      .then(this.display(plugins).bind(this));
```

2023-03-30 13:54 UTC, medikoo commented on lib/plugins/plugin/list.js
> +    return Promise.resolve(this)
It's not needed, you can write same as:

```javascript
async () {
  return this.getPlugins().then((plugins) => this.display(plugins));
}
```

and actually we can already refactor to async await as:

```javascript
async  list() {
  await this.display(await this.getPlugins());
}
```

2023-03-30 14:59 UTC, sleepwithcoffee commented on lib/plugins/plugin/list.js
> +    return Promise.resolve(this)
thanks for pointing it out, it was so obvious that I didn't think about it

2023-03-30 15:00 UTC, sleepwithcoffee commented on lib/plugins/plugin/search.js
> +    return Promise.resolve(this)
done

2023-03-31 14:32 UTC, medikoo approved these changes
Looks great 👍 Thank you!

2023-03-31 14:32 UTC, merged