Replace BbPromise usages
serverless/serverless pull request #11905
Opened 2023-04-08 15:42 UTC by sleepwithcoffee

Addresses: #7171

2023-05-09 08:42 UTC, medikoo requested changes
Thanks @sleepwithcoffee for taking care of that!

In general it looks really good, I've just suggested few changes

2023-05-09 08:42 UTC, medikoo commented on test/unit/lib/plugins/deploy.test.js
> +    it('should have hooks', () => expect(deploy.hooks).not.be.empty);
Same here (and in other places)

2023-05-09 08:42 UTC, medikoo commented on test/unit/lib/plugins/deploy.test.js
> +      return expect(deploy.hooks['before:deploy:deploy']()).to.eventually.be.rejectedWith(
Let's also change function to _async_

2023-05-09 16:26 UTC, sleepwithcoffee commented
for some reason, it's picking another branch, hmm
![image](https://github.com/serverless/serverless/assets/3896985/5dd6d58e-d6b8-493d-ace0-c91b9796fba5)

2023-05-12 17:04 UTC, medikoo approved these changes
Looks great 👍

2023-05-12 17:04 UTC, merged