feat: Support for Java17 as runtime for AWS Lambda functions
serverless/serverless pull request #11938
Opened 2023-04-28 05:47 UTC by debae

Adds java17 also as a supported runtime since this is now officialy supported : https://aws.amazon.com/blogs/compute/java-17-runtime-now-available-on-aws-lambda/

Closes issue #11937

2023-04-29 08:39 UTC, GrahamCampbell requested changes

2023-04-29 08:39 UTC, GrahamCampbell commented on docs/providers/aws/guide/functions.md
> +**Note:** Lambda SnapStart only supports the Java 11 and Java17 runtime and does not support provisioned concurrency, the arm64 architecture, the Lambda Extensions API, Amazon Elastic File System (Am
Missing space before 17.

2023-04-29 08:39 UTC, GrahamCampbell commented on docs/providers/aws/guide/functions.md
> +**Note:** Lambda SnapStart only supports the Java 11 and Java17 runtime and does not support provisioned concurrency, the arm64 architecture, the Lambda Extensions API, Amazon Elastic File System (Am
Also, runtime needs to be plural.

2023-05-02 11:37 UTC, debae commented on docs/providers/aws/guide/functions.md
> +**Note:** Lambda SnapStart only supports the Java 11 and Java17 runtime and does not support provisioned concurrency, the arm64 architecture, the Lambda Extensions API, Amazon Elastic File System (Am
This is fixed now

2023-05-05 07:16 UTC, debae commented
@GrahamCampbell can you please have another look at this PR

2023-05-05 09:55 UTC, GrahamCampbell commented
I don't have merge permission here. 🤷

2023-05-05 09:55 UTC, GrahamCampbell approved these changes

2023-05-11 15:33 UTC, merged