11879 warning for func package patterns
serverless/serverless pull request #11974
Opened 2023-05-16 18:37 UTC by Lokesh-Jawale

**Added warning if functions[].package is defined without package.individually set to true at service level or function level.**
Closes: #[11879](https://github.com/serverless/serverless/issues/11879)

2023-05-17 08:00 UTC, medikoo requested changes
@Lokesh-Jawale great thanks for giving it a spin

In general it looks good, however I think more appropriate place for this warning will be the point where were resolve the packaging rules (and package functions), so here: https://github.com/serverless/serverless/blob/ed15cb27aee68954c93d875da96274914943ad71/lib/plugins/package/lib/package-service.js#L101

A place where you've added the logic is responsible for compiling AWS CloudFormation template, so it's not that related to packaging

2023-05-18 07:45 UTC, medikoo requested changes
@Lokesh-Jawale that looks very good. I've just proposed some small improvements

2023-05-18 07:45 UTC, medikoo commented on lib/plugins/package/lib/package-service.js
> +        !this.serverless.service.package.individually &&
Let's remove those two lines, we're already in context where that is confirmed

2023-05-18 07:45 UTC, medikoo commented on lib/plugins/package/lib/package-service.js
> +          ' Serverless will ignore the patterns and the default packaging patterns will be applied.',
Let's maybe reword last line to:

```
The framework will ignore the patterns defined at the function level and apply only the service-wide ones
```

2023-05-18 17:01 UTC, Lokesh-Jawale commented
@medikoo thanks for the suggestions, I have updated the PR as per the suggestions.

2023-05-19 09:38 UTC, medikoo approved these changes
Thank you 👍

2023-05-19 09:39 UTC, merged