Local invoke AWS CF function resolution for env variable : Ref
serverless/serverless pull request #8198
Opened 2020-09-07 09:38 UTC by fredericbarthelet

Addresses: #7087 #8147

2020-09-07 09:41 UTC, fredericbarthelet commented
@medikoo I could add an intermediate service responsible for resolving both imports and refs in order to simplify invoke local code and abstracting away the different functions that can be resolved. Would you prefer such service to be implemented or do you like it better this way ?

2020-09-07 10:14 UTC, medikoo requested changes
Thank you @fredericbarthelet it looks good! Still let me know what you think about my suggetsions

> @medikoo I could add an intermediate service responsible for resolving both imports and refs in order to simplify invoke local code and abstracting away the different functions that can be resolved. Would you prefer such service to be implemented or do you like it better this way ?

Do you think, we can (and should) use it then in some other places? If yes, then yes I think it might be nice to abstract it away.

2020-09-07 10:14 UTC, medikoo commented on lib/plugins/aws/utils/resolveCfRefValue.js
> +      _.merge(sdkParams, { StackName: provider.naming.getStackName() })
Let's use `Objec.assign`

2020-09-07 10:14 UTC, medikoo commented on lib/plugins/aws/invokeLocal/index.js
> +      const fnRefPromises = _.entries(configuredEnvVars).map(([name, value]) => {
It'll be nicer to use one`map` iteration for both `'Fn::ImportValue'` and `'Ref'`

2020-09-07 14:58 UTC, fredericbarthelet commented
@medikoo I updated my PR with your comments. I don't see any use yet for a service requiring as well import and ref intrinsic functions. When the case arise, I shall implement such service.

2020-09-08 07:25 UTC, medikoo reviewed
Thank you @fredericbarthelet looks great. Still shouldn't we also mention support for `Ref` in docs here: https://github.com/fredericbarthelet/serverless/blob/13e1bf7a7d2aba877a2cbd6e3c0c59689fbe8964/docs/providers/aws/cli-reference/invoke-local.md#local-function-invocation-setting-environment-variables ?

2020-09-08 08:06 UTC, fredericbarthelet commented
@medikoo you're right, I updated the documentation as well :)

2020-09-08 08:12 UTC, medikoo approved these changes
Thank you @fredericbarthelet !

2020-09-08 08:13 UTC, merged