DX: Throw if missing RoleName in Custom function role
serverless/serverless pull request #8219
Opened 2020-09-10 19:07 UTC by DavidWells

If `RoleName` is missing in a [custom function role](https://www.serverless.com/framework/docs/providers/aws/guide/iam/#custom-iam-roles) this passes through `undefined` and single `sls deploy -f funcName` fails with a hard to decipher error: 

```
  Serverless Error ---------------------------------------

  ServerlessError: The role defined for the function cannot be assumed by Lambda.
      at /service/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:330:27
      at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

After turning on SLS_DEBUG I found the issue where the IAM role name was  `undefined`

```
Serverless: [AWS lambda 400 0.417s 0 retries] updateFunctionConfiguration({
  FunctionName: 'service-dev-addNewUser',
  Description: 'Add user test function. Gated by imported Managed policy',
  Handler: 'examples/new-user.handler',
  Role: 'arn:aws:iam::01200101001:role/undefined'
})
```

This PR will throw an error if this value is missing & the `updateFunctionConfiguration` won't be called with incorrect values

2020-09-14 08:05 UTC, medikoo requested changes
@DavidWells great thanks for stepping in. Still it's not clear to me what exactly why is the issue.

Why exactly we should require `RoleName` to be defined on custom defined role? (It's not required on AWS side)

Also note that change you propose introduce `ReferenceError` (`roleProperties` variable is used before it actually is defined)

2020-09-17 22:43 UTC, DavidWells commented
Without a `RoleName` defined, serverless passes through an `undefined` variable [here](https://github.com/serverless/serverless/pull/8219/files#diff-4cbb6c3b54085f7b84b5aea9b859bb1eR84). This results in `'arn:aws:iam::01200101001:role/undefined'`

```
Serverless: [AWS lambda 400 0.417s 0 retries] updateFunctionConfiguration({
  FunctionName: 'service-dev-addNewUser',
  Description: 'Add user test function. Gated by imported Managed policy',
  Handler: 'examples/new-user.handler',
  Role: 'arn:aws:iam::01200101001:role/undefined'
})
```

Example yml to reproduce

```yml
service: xyz

provider:
  name: aws
  runtime: nodejs12.x

functions:
  # Function with role assigned
  myFunc:
    handler: func.handler
    role: { Fn::GetAtt: [ MyCustomRole, Arn ] }

resources:
  Resources:
    MyCustomRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: MyCustomRole-${self:provider.stage}
        Description: IAM function for function
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action: sts:AssumeRole
```

2020-09-18 09:12 UTC, medikoo commented
Great thanks @DavidWells for explanations, all clear now!

Intention looks legitimate. Still patch is placed at wrong line (producing `ReferenceError`), and I believe we should throw `ServerlessError` (it's designated for _operational_ errors, so errors that signal problem with how user use the Framework, and not Framework itself)

2020-10-07 08:51 UTC, medikoo approved these changes
Thank you @DavidWells !

2020-10-07 08:53 UTC, merged