layers schema
serverless/serverless pull request #8299
Opened 2020-09-28 17:08 UTC by thewizarodofoz

Closes: #8015

2020-09-30 11:13 UTC, medikoo requested changes
Thank you @thewizarodofoz ! It'll be great to have that in, and it looks very promising, please see my remarks

2020-09-30 11:13 UTC, medikoo commented on lib/configSchema.js
> +                { type: 'string', pattern: '^\\d{12}$' },
I think pattern should be as here: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-layerversionpermission.html#cfn-lambda-layerversionpermission-principal

2020-09-30 11:13 UTC, medikoo commented on lib/configSchema.js
> +                { const: '*' },
I would remove it and rely on pattern as in AWS docs

2020-09-30 13:46 UTC, thewizarodofoz commented on lib/configSchema.js
> +    layers: {
So should I remove `layers` from `lib/configSchema.js` altogether? or keep the simple `{type: 'object'}` schema there?

2020-09-30 14:04 UTC, medikoo commented on lib/configSchema.js
> +    layers: {
I believe it should be moved completely, exactly in a same way as `resources` where moved with this commit: https://github.com/serverless/serverless/commit/6d7e96722721c8a5c614bea2802af7142011d35f

2020-09-30 15:49 UTC, medikoo requested changes
@thewizarodofoz thanks for update! It looks promising, still if I see correctly, in current form this schema is totally ignored.

To have it working,  we need to introduce exactly same changes as we did here https://github.com/serverless/serverless/commit/6d7e96722721c8a5c614bea2802af7142011d35f for `resources`
(note changes in  `lib/classes/ConfigSchemaHandler/index.js` and I think it'll be nice to add documentation line at  `docs/providers/aws/guide/plugins.md`)

2020-09-30 15:49 UTC, medikoo commented on lib/plugins/aws/provider/awsProvider.js
> +                      pattern: '\\d{12}|\\*|arn:(aws[a-zA-Z-]*):iam::\\d{12}:root',
I think we need to enclose it with `^` and `$`

2020-10-01 07:31 UTC, thewizarodofoz commented
> I think it'll be nice to add documentation line at `docs/providers/aws/guide/plugins.md`

@medikoo Not sure that I follow. If I understand correctly, `resources` is mentioned there in the context of "Definition for eventual top level "resources" section", but in this PR we said that `layers` is not a top level section (it's aws specific) so it will not be relevant to a new custom provider.

2020-10-01 07:51 UTC, thewizarodofoz commented
@medikoo I followed the same path as shown in 6d7e96722721c8a5c614bea2802af7142011d35f, hope it's fine.
If you can, I would like to know why those are needed, couldn't figure it out from the code.

2020-10-01 12:28 UTC, medikoo reviewed
> @medikoo Not sure that I follow. If I understand correctly, resources is mentioned there in the context of "Definition for eventual top level "resources" section", but in this PR we said that layers is not a top level section (it's aws specific) so it will not be relevant to a new custom provider.

`layers` actually remain top-level, we didn't change that. We just moved it's definition to AWS context.

In this PR we move it's definition, and a capability to define `layers` through `defineProvider` schema extension utility, and to have that fully complete, it'll be great to also expose in docs that `layers` can be defined via `defineProvider`. See full docs for `defineProvider`: https://github.com/serverless/serverless/blob/6d7e96722721c8a5c614bea2802af7142011d35f/docs/providers/aws/guide/plugins.md#defineprovider-helper

2020-10-01 14:25 UTC, medikoo reviewed
That looks great @thewizarodofoz !

Sorry for still not yet taking it in, but today one improvement landed which I believe will vastly improve service configuration handling, and which allows us to simply schema as proposed here. Please see my comment

2020-10-01 14:25 UTC, medikoo commented on lib/plugins/aws/provider/awsProvider.js
> +                    { type: 'integer', minimum: 100000000000, maximum: 999999999999 },
Today I've turned on automatic coercion with https://github.com/serverless/serverless/pull/8319, and having that I believe we  no longer need that `number` definition.

We can also remove the logic which tries to handle eventual numeric input

2020-10-01 15:39 UTC, medikoo approved these changes
Thank you @thewizarodofoz ! That looks great

2020-10-01 15:39 UTC, merged