fix(AWS Deploy) Not to delete .serverless directory after deploy
serverless/serverless pull request #8334
Opened 2020-10-02 13:45 UTC by s-kikuchi

## Issue
https://github.com/serverless/serverless/issues/7298

## Summary
- Fix not to copy the context of -p (p is the option for deploy command) directory into `.serverless` directory when executing the command `sls deploy -p /path/to/content`
- Fix not to copy the content that is `package.path` in `serverless.yml` into `.serverless` directory when executing the command `sls deploy`
- Fix to not delete .serverless directory after deployment

2020-10-05 12:38 UTC, medikoo requested changes
@s-kikuchi thanks for giving that a spin.

Still, have you tested it? As I test it, this technically breaks support for `--package` argument, deployments with it, no longer work

2020-10-06 10:25 UTC, s-kikuchi commented
@medikoo 
Thank you for your response.

> Still, have you tested it? As I test it, this technically breaks support for --package argument, deployments with it, no longer work

I have tested it and I couldn't confirm that error when executing the deploy command with `--package` option.
If it's ok, could you tell me
- whole execution command with option
- the error messages displayed

I would like to reproduce.

2020-10-06 12:06 UTC, medikoo commented
@s-kikuchi Running `sls deploy --package package` from this branch against this simple (and perfectly valid) service https://github.com/medikoo/test-serverless/tree/package-path produces following error:

```
sls deploy --package package
 
  Serverless Error ---------------------------------------
 
  No function.zip file found in the package path you provided.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.13.0
     Framework Version:         2.4.0
     Plugin Version:            4.0.4
     SDK Version:               2.3.2
     Components Version:        3.2.1
```

2020-11-30 13:09 UTC, medikoo commented
@s-kikuchi great thanks for an attempt on addressing that. It appeared a more challenging than I initially thought, and I've preapred a full spec on how to tackle that in main description of the issue https://github.com/serverless/serverless/issues/7298

I'm going to close this one, as it's in active, and after all requires quite different approach. Still if you wish to continue work on it, it's definitely very welcome. We just need to first agree on spec as outlined in above issue, and ensure to not break anything.

2020-11-30 13:09 UTC, closed without merging