bug(AWS API Gateway): Change order in naming of API Gateway
serverless/serverless pull request #8339
Opened 2020-10-03 15:04 UTC by fabsrc

BREAKING CHANGE:
The naming of API Gateway was changed from `${stage}-${service}` to `${service}-${stage}`

Closes: #2918

2020-10-05 15:25 UTC, medikoo requested changes
Thanks @fabsrc for giving that a spin!

Sorry for not having that clear in origin issue, but we cannot introduce breaking changes just like that. All breaking changes are first introduced as deprecation, and then when new major is about to be released we issue a PR's that make changes actually breaking.

I've updated the main description of https://github.com/serverless/serverless/issues/2918 with implementation proposal. Please see notes over there, on how it should be approached.

Thank you!

2020-10-10 13:24 UTC, fabsrc commented
Hey @medikoo.

Thanks for the detailed description how to implement this. Makes a lot of sense to do it that way.
I added the deprecation notice and an option to enable the new convention already.

Could you please have another look?

2020-10-12 09:47 UTC, medikoo requested changes
Thank you @fabsrc ! That looks really good. I've proposed few final improvements

2020-10-12 09:47 UTC, medikoo commented on lib/plugins/aws/lib/naming.js
> +      'Starting with next major version, API Gateway naming will be changed from `${service}-${stage}` to `${stage}-${service}`.'
Let's rephrase it to:

```
Starting with next major version, API Gateway naming will be changed from "{stage}-{service}" to "{service}-{stage}"
Set "provider.apiGateway.shouldStartNameWithService" to "true" to  adapt to new behavior now
```

2020-10-12 09:47 UTC, medikoo commented on lib/plugins/aws/provider/awsProvider.js
> +                shouldStartNameWithService: { type: 'boolean' },
Let's set it as `const: true`. If we would allow also `false`, it'll mean that we should keep support for old way of things in v3.

2020-10-12 09:47 UTC, medikoo commented on lib/plugins/aws/provider/awsProvider.js
> +                shouldStartNameWithService: { type: 'boolean' },
Let's define properties in alphabetical order

2020-10-14 10:13 UTC, medikoo reviewed
Thank you @fabsrc, looks very good. Just few last style suggestions

2020-10-14 10:13 UTC, medikoo commented on docs/providers/aws/guide/serverless.yml.md
> +    shouldStartNameWithService: true # Use `${service}-${stage}` naming for API Gateway. Will be `true` by default in next major version.
In this doc, we need to expose defaults. So let's keep `false` (even though we explictly do not suport such setting). 
Technically we could set `null`, as that'll be valid on schema grounds, but then again it'll be confusing

2020-10-14 10:13 UTC, medikoo commented on lib/plugins/aws/lib/naming.js
> +      this.provider.serverless.service.provider.apiGateway.shouldStartNameWithService === true
Let's write it as:

```javascript
if (_.get(this.provider.serverless.service.provider.apiGateway, "shouldStartNameWithService")) {
..
```

It's not natural in JS to check for `true` explicitly

2020-10-15 08:44 UTC, medikoo reviewed
@fabsrc thanks for update. Can you rebase with master? Currently PR has some conflicts and is not in mergeable state

2020-10-19 09:58 UTC, medikoo approved these changes
Thank you @fabsrc !

2020-10-19 09:59 UTC, merged

2020-11-16 16:36 UTC, Poonaka commented
Will there be a way to keep the old naming convention in future releases?

2020-11-16 17:17 UTC, medikoo commented
> Will there be a way to keep the old naming convention in future releases?

Thanks for asking. Currently we want to drop support for old naming intermittently with new version, still we're open for feedback on that. 

Do you find it problematic if v3 will not support old naming?

2020-11-16 17:52 UTC, Poonaka commented
> > Will there be a way to keep the old naming convention in future releases?
> 
> Thanks for asking. Currently we want to drop support for old naming intermittently with new version, still we're open for feedback on that.
> 
> Do you find it problematic if v3 will not support old naming?

We used serverless to setup some Cognito user pools and lambda triggers that occasionally need to be updated. Just wondering how we will migrate to the new naming convention without serverless deleting the user pools.

2020-11-16 18:50 UTC, fabsrc commented
> Will there be a way to keep the old naming convention in future releases?

I think by explicitly setting the name of the API Gateway in the provider settings (`provider.apiName`) you can keep the old convention. E.g.

```yaml
provider:
  name: aws
  apiName: ${opt:stage, 'dev'}-${self:service.name}
```

2020-11-16 19:11 UTC, Poonaka commented
> > Will there be a way to keep the old naming convention in future releases?
> 
> I think by explicitly setting the name of the API Gateway in the provider settings (`provider.apiName`) you can keep the old convention. E.g.
> 
> ```yaml
> provider:
>   name: aws
>   apiName: ${opt:stage, 'dev'}-${self:service.name}
> ```

Perfect, we will give that a shot. Thanks!

2020-11-17 08:21 UTC, medikoo commented
@fabsrc that's a great hint. Also using `apiName` will turn off the deprecation notice. So that technically the recommended way to carry on without change in next major. I'll add that info to deprecation notes