Update documentation
serverless/serverless pull request #8407
Opened 2020-10-17 13:19 UTC by AndriyTykhan

Document logical id generation for path variables in urls

Closes: #{ISSUE_NUMBER}

2020-10-17 13:20 UTC, AndriyTykhan commented
@pmuens  could you review it?

2020-10-19 10:08 UTC, medikoo requested changes
Thank you @AndriyTykhan ! That looks good, I've pointed just one small typo.

Concerning Hackoctoberfest we do not officially participate, but we welcome and value quality contributions at any time.

2020-10-19 10:08 UTC, medikoo commented on docs/providers/aws/guide/resources.md
> +If you have path variables in your url, they get normalized too, and there is a `Var` added implicity. So `normalizedPath` for `POST /users/{user_id}` will be normalized to `UsersUseridVarTestPost`
*implicitly

2020-10-23 10:50 UTC, AndriyTykhan commented on docs/providers/aws/guide/resources.md
> +If you have path variables in your url, they get normalized too, and there is a `Var` added implicity. So `normalizedPath` for `POST /users/{user_id}` will be normalized to `UsersUseridVarTestPost`
Thanks, I've fixed it

2020-10-28 11:04 UTC, medikoo approved these changes
Thank you @AndriyTykhan !

2020-10-28 11:05 UTC, merged