Add cross plugin event definition
serverless/serverless pull request #8471
Opened 2020-11-04 16:52 UTC by fredericbarthelet

Closes: #8438

2020-11-04 19:44 UTC, medikoo requested changes
Thank you @fredericbarthelet ! Looks very good, please see my comments.

Also it'll be great to add documentation as it was added in https://github.com/serverless/serverless/pull/8462

2020-11-04 19:44 UTC, medikoo commented on lib/classes/ConfigSchemaHandler/index.js
> +  extendFunctionEventDefinition(providerName, name, configSchema) {
To match convention of other methods, let's name it `defineFunctionEventProperties`

2020-11-04 19:44 UTC, medikoo commented on lib/classes/ConfigSchemaHandler/index.js
> +      return;
Let's crash with meaningful error here

2020-11-04 19:44 UTC, medikoo commented on lib/classes/ConfigSchemaHandler/index.js
> +    ].properties.events.items.anyOf.findIndex(
It might be cleaner to use `find` and save result to e.g. `eventDefinition` property. Then we don't have to repeat this long access path below

2020-11-06 08:42 UTC, fredericbarthelet commented
@medikoo, I implemented your comments and added documentation. Let me know what you think :)

2020-11-06 12:11 UTC, medikoo requested changes
@fredericbarthelet Looks great! Just few last minor remarks and we'll be good to go

2020-11-06 12:11 UTC, medikoo commented on docs/providers/aws/guide/plugins.md
> +This way, if user sets `documentation` by mistake to `5`, the Framework would display an error:
This statement is actually not true, as we're doing coercion `5` will be accepted as `"5"` :)

Bullet proof example would be to for example use object where primitive is expected and other way

2020-11-06 12:11 UTC, medikoo commented on test/fixtures/configSchemaExtensionsError/test-plugin-with-errors.js
> +          events: {
Function events should be passed through `functionEvents` option.

Passing events that way seems error-prone (I see it as an issue that `defineProvider` didn't crash - I believe we should improve those methods so they do not allow overwrites - just opened an issue to address that: https://github.com/serverless/serverless/issues/8481)

2020-11-06 13:46 UTC, fredericbarthelet commented
@medikoo changed `events` to `functionEvents`. Thanks for noticing :)

2020-11-06 13:53 UTC, medikoo approved these changes
Thank you @fredericbarthelet !

2020-11-06 13:53 UTC, merged