fix(AWS Lambda Layers): Permissions on lambda layer retained
serverless/serverless pull request #8579
Opened 2020-12-04 17:03 UTC by raym0nd93

Closes: #8578

2020-12-07 12:20 UTC, medikoo requested changes
Thank you @raym0nd93 ! Does it confirm to fix the issue on your side?

Can we configure one regression test in scope of this describe block: https://github.com/serverless/serverless/blob/9bdcb4fc17ad06faf0c666f33850fee6d3cd6a6c/test/unit/lib/plugins/aws/package/compile/layers/index.test.js#L360

2020-12-07 12:26 UTC, raym0nd93 commented
Yes I've tested the code as it is in the MR, it did retain the permission on the lambda layer.

2020-12-07 17:13 UTC, raym0nd93 commented
I'm not 100% sure if this is what you meant, any feedback is very welcome

2020-12-08 08:26 UTC, medikoo requested changes
@raym0nd93 thanks for update! Please see my comment, also note that CI started to fail.

Did you intentionally converted the PR into draft?

2020-12-08 08:26 UTC, medikoo commented on test/unit/lib/plugins/aws/package/compile/layers/index.test.js
> +      expect(layerPermissionResource.DeletionPolicy).to.equal('Retain');
Let's put it in another `it`, so it serves as individual spec item.

I'd probably name it: _should retain permission resource_

2020-12-20 20:00 UTC, pgrzesik commented
Hello @raym0nd93, thanks a lot for your contributions to this PR :bow: We'd like to wrap it up in the coming days, so I hope you don't mind me taking over your work and applying the finishing changes. Please let me know if you'd still like to continue your work here. Once again, your help is much appreciated :bow:

2020-12-30 10:26 UTC, pgrzesik commented
Closing this one in favor of https://github.com/serverless/serverless/pull/8688

2020-12-30 10:26 UTC, closed without merging