refactor: Remove dependency to stream-promise
serverless/serverless pull request #8601
Opened 2020-12-10 08:47 UTC by juanjoDiaz

Just noticed that `stream-promise` was used only once in the solution and it's something that we can do using native node

2020-12-10 16:51 UTC, medikoo requested changes
Thank you @juanjoDiaz. That's a great pick! I have just one naming suggestion, let me know what you think

2020-12-10 16:51 UTC, medikoo commented on lib/plugins/standalone/index.js
> +const pipelineAsync = promisify(pipeline);
I think we can keep it named `pipeline` or  `piplinePromised` (it was _async_ already, so `pipelineAsync` is slightly confusing)

e.g. in other files convention of naming is as https://github.com/serverless/serverless/blob/d102a3984abfe5c014c4adafa8abf2ea8edfd336/lib/utils/eventuallyUpdate.js#L20

2020-12-10 18:13 UTC, juanjoDiaz commented
Done.

Btw, why is it needed a tempo file?
```js
    await fse.remove(BINARY_TMP_PATH);
    await pipeline(standaloneResponse.body, fs.createWriteStream(BINARY_TMP_PATH));
    await fse.rename(BINARY_TMP_PATH, BINARY_PATH);
    await fse.chmod(BINARY_PATH, 0o755);
```

Why not:
```js
    await pipeline(standaloneResponse.body, fs.createWriteStream(BINARY_PATH, { mode: 0o755 }));
```

I can add a second commit for that, or a separate PR after this one.

2020-12-10 19:43 UTC, medikoo commented
> Why not

As if process will crash in a middle for some reason (or simply there will disconnection) user will be left with broken binary. 

We first download it on a side and then exchange it "immediately"

2020-12-14 12:02 UTC, medikoo approved these changes
Thank you @juanjoDiaz !

2020-12-14 12:03 UTC, merged