Implement invoke client context
serverless/serverless pull request #8652
Opened 2020-12-21 16:11 UTC by lewgordon

Closes: 8644

2020-12-21 17:13 UTC, medikoo requested changes
Thank you @lewgordon ! It looks really good. I've proposed some improvements, let me know what you think

2020-12-21 17:13 UTC, medikoo commented on lib/plugins/aws/invoke.js
> +            this.options[rawDataKey] = await stdin();
This should be applied only to `data` resolution. 

I think this means that using `for .. of` as proposed is probably not best choice

2020-12-21 17:13 UTC, medikoo commented on lib/plugins/aws/invoke.js
> +      if (typeof this.options.context === 'object') {
Let's do reverse condition `if (typeof this.options.context !== 'string')`, it'll be more bulletproff

2020-12-21 17:13 UTC, medikoo commented on lib/plugins/aws/invoke.js
> +        this.options.context = JSON.stringify(this.options.context);
Let's not override `context` on `this.options` (it's introduces side effect for eventual external consumers of the option)

2020-12-21 17:13 UTC, medikoo commented on test/unit/lib/plugins/aws/invoke.test.js
> +        Payload: sinon.match({}),
Does this work with `chai.expect` ? 

Alternatively, we can probably use `args[0][0]` and `deep.equals` (?)

2020-12-21 17:13 UTC, medikoo commented on test/unit/lib/plugins/aws/invoke.test.js
> +      awsInvoke.options.context = null;
Let's not edit and extend those tests (they're scheduled for full rewrite, and  new`runServerless` based tests should cover all we need)

2020-12-21 18:20 UTC, lewgordon commented
With the requested changes, I'm missing a line of coverage for around the ENOENT check.  I wasn't sure if there was an easy way to test it with my proposed changes.

2020-12-22 15:41 UTC, medikoo requested changes
Thank you @lewgordon ! Please see my remarks

2020-12-22 15:41 UTC, medikoo commented on lib/plugins/aws/invoke.js
> +    }
I think we should follow exactly same logic as with data input, so:
1. Attempt to _parse_ if no `--raw` option was passed
2. In all cases `JSON.stringify` when assigning to params

2020-12-22 15:41 UTC, medikoo commented on lib/plugins/invoke.js
> +            shortcut: 'x',
Let's remove that shortcut

(I've just realized we've embraced them originally on `invoke local`, but they are error prone, and I believe it's better to remove them from `invoke local` at some point, than embracing same pattern here)

2020-12-22 15:41 UTC, medikoo commented on test/unit/lib/plugins/aws/invoke.test.js
> +const runServerless = require('../../../../utils/run-serverless');
I've created a base for new tests in this file (was just merged to master, and also opened issue that welcomes the refactor of tests in this file: https://github.com/serverless/serverless/issues/8662)

I propose to add following tests here: https://github.com/serverless/serverless/blob/b72a910604b4e7d3dc3da267f47e5ed41a34d551/test/unit/lib/plugins/aws/invoke.test.js#L456

- ``should support `--context` param``
- ``should support `-contextPath` param``

And simply unskip and configure missing parts.

2020-12-23 12:21 UTC, medikoo requested changes
Thank you @lewgordon ! It looks really good, I have just few last minor suggestions

2020-12-23 12:21 UTC, medikoo commented on test/unit/lib/plugins/aws/invoke.test.js
> +    fse.writeFileSync(contextDataFile, JSON.stringify(data));
Instead of writing file, let's add `context.json` file to the `invocation` fixture (we already have there `payload.json` etc.)

2020-12-23 12:21 UTC, medikoo commented on test/unit/lib/plugins/aws/invoke.test.js
> +    ).to.be.rejectedWith('The file you provided does not exist.');
Let's confirm on `error.code` (`this.serverless.classes.Error` as second argument takes _code_).

Error message is subject to improvements, `code` is expected to be set once and is dedicated for programmatic usage

2020-12-23 12:21 UTC, medikoo commented on test/unit/lib/plugins/aws/invoke.test.js
> +  it('should allow invoke with raw context for contextPath', async () => {
By content this test looks as duplicate of `should support `--contextPath` param`.

What's the purpose of it?

2020-12-23 14:02 UTC, medikoo approved these changes
Looks great! Thank you @lewgordon

2020-12-23 14:03 UTC, lewgordon commented
@medikoo thank you for your time and help!

2020-12-23 14:03 UTC, merged