test: Refactor some tests for AWS invoke to use runServerless.
serverless/serverless pull request #8668
Opened 2020-12-23 18:40 UTC by lewgordon

I tried taking a first stab at this.  One of the tests I moved out the common section as I thought it would be easier to implement the test in that way.  I figured a smaller PR would potentially help me get a feel for what your thoughts are on how to implement these tests.

Addresses: #8662

2020-12-28 10:01 UTC, pgrzesik requested changes
Hello @lewgordon :wave: You're totally on the right path when it comes to implementing these :raised_hands: I've posted a few suggestions, but overall it looks good :raised_hands:

2021-01-04 13:56 UTC, lewgordon commented on test/unit/lib/plugins/aws/invoke.test.js
> +  it('should log payload', async () => {
Sure, I think I follow you there. I kept the assertions too, though. Not sure if that now makes `should invoke AWS SDK with expected params` mostly redundant?

2021-01-05 09:49 UTC, pgrzesik commented on test/unit/lib/plugins/aws/invoke.test.js
> +  it('should log payload', async () => {
I agree that now we have redundancy/duplication across these two tests. I believe we could keep the `should invoke AWS SDK with expected params` as-is and remove assertions on a `stub` from `should log payload`, so it only confirms logs on stdout. What do you think?

2021-01-05 09:49 UTC, pgrzesik requested changes
Looks great :raised_hands: Please see my last comment and I believe after that we'll be good to go :+1:

2021-01-05 14:30 UTC, lewgordon commented on test/unit/lib/plugins/aws/invoke.test.js
> +  it('should log payload', async () => {
I think that is reasonable!

2021-01-05 16:01 UTC, pgrzesik requested changes
Looks great, thank you @lewgordon. Sorry for the trouble, but I think you'll need to rebase on top of master as we introduced `prettier` in `v2` yesterday and current linting/formatting validation is failing on your branch due to that.

2021-01-06 09:44 UTC, pgrzesik approved these changes
Thank you @lewgordon, awesome job :+1:

2021-01-06 09:44 UTC, merged