Move rest api specific keys from provider level to provider.apiGateway level
serverless/serverless pull request #8670
Opened 2020-12-24 10:11 UTC by fredericbarthelet

Closes: #8617

2020-12-28 09:29 UTC, pgrzesik requested changes
Well done :raised_hands: I only have minor comments and otherwise it looks good to go :+1:

2020-12-28 09:29 UTC, pgrzesik commented on docs/deprecations.md
> +## `awsKmsKeyArn` references
I believe this is a leftover, maybe it could say "API Gateway-specific configuration" or something along those lines?

2020-12-28 09:29 UTC, pgrzesik commented on docs/deprecations.md
> +Starting with v3.0.0, API Gateway-specific configuration keys "apiKeys", "resourcePolicy" and "usagePlan" will be relocated from "provider" to "provider.apiGateway".
Minor nitpick: I believe that across this doc we're using backticks instead of "" to highlight specific configuration keys

2020-12-28 09:29 UTC, pgrzesik commented on docs/providers/aws/guide/serverless.yml.md
> +  rollbackConfiguration:
Good catch with fixing it :raised_hands:

2021-01-03 17:18 UTC, fredericbarthelet commented
Thanks for your review @pgrzesik. I implemented your comments and rebased on latest master revision.

2021-01-04 09:00 UTC, pgrzesik approved these changes
Well done, thank you @fredericbarthelet :bow:

2021-01-04 09:04 UTC, merged