[  ]
serverless/serverless pull request #8753
Opened 2021-01-13 20:27 UTC by caiobessa

This PR is about refactoring test/unit/lib/plugins/aws/package/compile/layers/index.test.js to runServerless based variant.

Closes: #8585

2021-01-14 17:57 UTC, pgrzesik requested changes
Thanks @caiobessa, great job! I had a few suggestions for improvements, please see my comments and let me know what you think :bow: 

Btw - comment about using `to.equal` applies to all test cases but I didn't want to repeat it multiple times.

2021-01-14 17:57 UTC, pgrzesik commented on test/unit/lib/plugins/aws/package/compile/layers.test.js
> +    expect(layerResource.Properties.Content.S3Key).to.be.equal(`${s3Folder}/${s3FileName}`);
let's use `to.equal` instead of `to.be.equal`

2021-01-14 17:57 UTC, pgrzesik commented on test/unit/lib/plugins/aws/package/compile/layers.test.js
> +    expect(layerResource.Type).to.be.equals('AWS::Lambda::LayerVersion');
in assertions in this test also let's use `to.equal` instead of `to.be.equal`/`to.be.equals`

2021-01-14 17:57 UTC, pgrzesik commented on test/unit/lib/plugins/aws/package/compile/layers.test.js
> +    const layerResourceName = naming.getLambdaLayerLogicalId('LayerOne');
let's only validate that we have the expected permission resource as a part of this test as the assertions about `layer` type, etc are duplicated with the tests above

2021-01-14 17:57 UTC, pgrzesik commented on test/unit/lib/plugins/aws/package/compile/layers.test.js
> +    const layerResourceName = naming.getLambdaLayerLogicalId('LayerTwo');
Here also let's just validate support for `allowedAccounts` and remove all assertions that were already performed in previous tests

2021-01-17 02:15 UTC, caiobessa commented
@pgrzesik Thanks for the all suggestions, the code now is cleaner 🥇 

If you have more suggestions  please let me know.

2021-01-17 19:57 UTC, pgrzesik approved these changes
Thanks @caiobessa, awesome job :raised_hands:

2021-01-17 20:00 UTC, merged