Very descriptive comment on usage of deploy function
serverless/serverless pull request #8756
Opened 2021-01-13 21:28 UTC by jugglingjsons

Q1: https://github.com/serverless/serverless/issues/8752

Based on discussion here https://github.com/serverless/serverless/issues/8752
Basically when you have provisionedConcurrency set you can be confused as to why your lambdas are not updating after you run this command.
Looking for pointers where it belongs if not here

Closes: #{8752}

2021-01-13 21:40 UTC, jugglingjsons commented
Not sure if this still counts as docs, but happy to put it anywhere else it needs to go :)

2021-01-15 10:37 UTC, pgrzesik commented
Hello @jugglingjsons, thanks for submitting this proposal. I believe we should include this type of information in docs (see https://github.com/serverless/serverless/blob/master/docs/providers/aws/cli-reference/deploy-function.md and https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/deploying.md) instead of including longer description in `usage`. What do you think?

2021-01-15 11:09 UTC, jugglingjsons commented
> Hello @jugglingjsons, thanks for submitting this proposal. I believe we should include this type of information in docs (see https://github.com/serverless/serverless/blob/master/docs/providers/aws/cli-reference/deploy-function.md and https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/deploying.md) instead of including longer description in `usage`. What do you think?

Sure, agreed! But I believe there should be at least a short-link to this more descriptive explanation in the cli. WDYT?

2021-01-15 11:38 UTC, pgrzesik commented
Reference to docs about limitations sounds good to me @jugglingjsons :+1:

2021-01-29 09:10 UTC, jugglingjsons commented
Updated, please check and verify. I've chosen to put it in one of the .md s only for now. The other seems to be a more general stack deployment guide.

2021-01-31 12:24 UTC, pgrzesik requested changes

2021-01-31 12:24 UTC, pgrzesik commented on docs/providers/aws/cli-reference/deploy-function.md
> +cycles and not production deployments. Some parts of serverless configuration
Let's maybe rewrite it to something more like:

During `deploy function`, only changes that can be applied via `updateFunctionCode` and `updateFunctionConfiguration` direct `aws-sdk` calls will take effect. It is important to remember that configuration that is related to separate CloudFormation resources will not be updated. The function that is triggered through an alias will be updated, but the alias itself won't. One instance of that might be when using the `provisionedConcurrency`.

2021-01-31 12:24 UTC, pgrzesik commented on lib/plugins/deploy.js
> +              'Deploy a single function from the service. It has limitations - read more here: https://github.com/serverless/serverless/blob/master/docs/providers/aws/cli-reference/deploy-function.md
After second though, I would remove that note. I've looked around and we do not practice linking to documentation in `usage` for specific commands + it's a general `function` command that is not only related to AWS provider, which will be confusing to people that use different providers.

2021-08-31 14:09 UTC, pgrzesik commented
I'm going to close this one due to inactivity

2021-08-31 14:09 UTC, closed without merging