fix: Properly resolve local version
serverless/serverless pull request #8899
Opened 2021-02-05 12:52 UTC by pgrzesik

Attempt to fix situation where `sls --version` or version reported with thrown error is not accurate if local installation of Serverless is involved

2021-02-05 12:53 UTC, pgrzesik commented on lib/cli/eventually-list-version.js
> +        );
I'm starting to lose my sanity while trying to satisfy `eslint` that keeps throwing:
```
52:50  error  Expected to return a value at the end of async arrow function  consistent-return
```

I think I've tried like 10 different approaches here - do you see an obvious mistake here or maybe have a suggestion on how to satisfy `eslint`? I believe it's not possible for this function to not return (or throw an error).

2021-02-05 12:54 UTC, pgrzesik commented
I've tested it all locally in different scenarios, but I'm not sure how to properly write automated tests for it as setup is quite complicated and requires multiple framework versions to be available. What is your suggestion here @medikoo ?

2021-02-05 15:28 UTC, medikoo requested changes
@pgrzesik looks very good. I have just few points

> I've tested it all locally in different scenarios, but I'm not sure how to properly write automated tests for it as setup is quite complicated and requires multiple framework versions to be available. What is your suggestion here @medikoo ?

Yes, testing it automatically is maintenance wise quite expensive, while feature is temporary and not critical (addresses side edge case).

Great you've tested locally all cases, and I'd say that's good enough in this case.

2021-02-05 15:28 UTC, medikoo commented on lib/cli/handle-error.js
> +          serverless: { isLocallyInstalled },
I believe we need to also pass `forceExit: isUncaughtException`

2021-02-05 15:28 UTC, medikoo commented on lib/cli/eventually-list-version.js
> +    // If the version is already local, do not try to fallback for version resolution to avoid falling into the loop
Let's also add a comment:

```
// TODO: Remove local version fallback with next major (when its moved to the top of the process)
```

(When releasing a new major I'd search for all TODO comments in codebase and ensure we've addressed them)

I'd add also this comment to error handler

2021-02-08 08:42 UTC, pgrzesik commented on lib/cli/eventually-list-version.js
> +          return require(path.resolve(localServerlessPath, '../../bin/serverless'));
The resolution against `filepath` works as intended, but I really like your solution from readability perspective - I'll change it :+1:

2021-02-08 09:19 UTC, pgrzesik commented
Thanks for all suggestions and for pointing out the obvious issue with linter :facepalm:

2021-02-08 10:04 UTC, medikoo approved these changes
Looks great 👍

2021-02-08 10:06 UTC, merged