refactor: Remove bluebird from classes
serverless/serverless pull request #8943
Opened 2021-02-14 23:37 UTC by juanjoDiaz

Addresses: #7171

2021-02-15 08:15 UTC, pgrzesik commented
Hello @juanjoDiaz :wave: Thanks a lot for proposed changes. Before continuing with review, I have a question to @medikoo as I know you're currently working on refactoring variables resolution as a part of https://github.com/serverless/serverless/issues/8364 - is the refactor to `Variables.js` conflicting with your current work? Does it make sense to accept refactorings to that part at the moment or it's going to be removed soon anyway? Thanks :bow:

2021-02-15 16:03 UTC, medikoo commented
> @medikoo as I know you're currently working on refactoring variables resolution as a part of #8364 - is the refactor to Variables.js conflicting with your current work?

@pgrzesik thanks for asking. I did not touch any part of old implementation. It's that new parser will simply take over, and older will only eventually serve as fallback, in case a new parser will report errors.

2021-02-15 18:51 UTC, juanjoDiaz commented
Fixed the issues that @pgrzesik raised.

Any idea of why might the pipeline be failing?
My last commit only touched docs, and the build was passing before.

2021-02-16 10:21 UTC, pgrzesik reviewed
Hello @juanjoDiaz :wave: Thanks a lot - in general it looks good, but according to the original issue, in the first step we should address marking all promise-returning functions as `async` - here we have more refactoring, but not all promise-returning functions are marked as async. We also have a related PR that addreses that first part for `Variables.js` here: https://github.com/serverless/serverless/pull/8942 

To keep things in order, I believe the above PR should be resolved first and then we can continue with that refactoring. What is your opinion here @juanjoDiaz ?

2021-02-16 20:23 UTC, juanjoDiaz commented
Oh I haven't seen that other PR.

I think that it makes sense to use `async` when you also use `await`.
I could review this PR and add async to any function that returns a promise but doesn't use async.

Apart from removing BbBluebird, this PR remove unnecessary promise wrappers and replace `then.catch` chains with `async/await`-style code.

If you rather waiting for the other PR and then check this, that's also fine.

2021-02-18 09:18 UTC, pgrzesik requested changes
I agree that it makes sense - the problem with these changes is that they often can introduce bugs that are very hard to catch during review process, especially when the scope of the PR is bigger, that's why we suggested to migrate it gradually by first marking functions as `async`, removing unnecessary promise wrapers and only then getting rid of all BbPromise usages. But to not re-do the work you already did I think we should wrap up the changes as a part of this PR - the only thing that would be good here is if you could review the methods that are returning a promise and mark them as async if they're not marked as such yet. I also added a few comments related to `Promise.resolve` usage that I think we could get rid of

2021-02-18 09:18 UTC, pgrzesik commented on lib/classes/Variables.js
> +    return Promise.resolve(valueToPopulate);
Can we just mark it as `async` and return the value?

2021-02-18 09:18 UTC, pgrzesik commented on lib/classes/Variables.js
> +    return Promise.resolve(valueToPopulate);
Can we just mark it as `async` and return the value?

2021-02-18 09:18 UTC, pgrzesik commented on lib/classes/Variables.js
> +    return Promise.resolve(valueToPopulate);
Can we just mark it as `async` and return the value?

2021-02-18 09:18 UTC, pgrzesik commented on lib/classes/Variables.js
> +    return Promise.resolve(valueToPopulate);
Can we just mark it as `async` and return the value?

2021-02-18 09:18 UTC, pgrzesik commented on lib/classes/Variables.js
> +    return Promise.resolve(valueToPopulate);
Can we just mark it as `async` and return the value?

2021-02-18 09:18 UTC, pgrzesik commented on lib/classes/Variables.js
> +    return Promise.resolve(valueToPopulate);
Can we just mark it as `async` and return the value?

2021-02-18 09:18 UTC, pgrzesik commented on lib/classes/Variables.js
> +    return Promise.resolve(
Let's mark the function as async instead of using `Promise.resolve` construct

2021-02-18 19:46 UTC, juanjoDiaz commented
I've marked all the functions returning promises as `async`.

I have the feeling that quite a few of the async functions in `Variables.js` are synchronous functions and the whole thing could be simplified but I didn't want to go there.

2021-02-19 12:42 UTC, pgrzesik requested changes
Thank you @juanjoDiaz - awesome job :raised_hands: However, I believe that I've made a mistake in my previous suggestions as I kinda missed the fact that these functions are not async at all - could you please check if we can just drop `async` from them? Other than that, we should be good to go :100: 

As for any further refactoring - at this point I think we shouldn't really refactor `Variables.js` as @medikoo is working on introducing totally new variables parser, which should make this one obsolete at some point in the future.

2021-02-19 15:25 UTC, juanjoDiaz commented
Hi @pgrzesik,

The function as nor async but are called in a way that things break if you make them sync.

I was planning to raise a ticket about that once this PR is merged.
If the intention is to leave this as an obsolete class, I wouldn't really go into that change.

2021-02-19 17:02 UTC, pgrzesik approved these changes
Thank you @juanjoDiaz for verifying if we can drop `async` - all looks great now :bow:

2021-02-19 17:03 UTC, merged