fix(Templates): Properly package `gradle-wrapper` into npm package
serverless/serverless pull request #8967
Opened 2021-02-18 14:01 UTC by pgrzesik

Bug discovered when working on #8406 - it turns out that it's not possible to package files with `.jar` extensions into npm package. I've tried explicitly including it via `npmignore` in a similar manner to `.gitignore` but it didn't work. I've also confirmed that our latest version published does not include these `jar`s. After implementing the fix, I've confirmed that it's working correctly by running tests against a package generate with `npm pack`.

2021-02-18 15:35 UTC, medikoo requested changes
@pgrzesik I looked into that, and was not able to reproduce the problem.

On my side `npm pack` packs `graddle-wrapper.jar` files without any further settings.

Also those files seem to be packaged with currently published version, you can inspect it  at https://npmview.now.sh/serverless (unfortunately we cannot link to specific file, but by traversing into `lib/plugins/create/templates/aws-clojure-gradle/gradle/wrapper`, you can confirm that `gradle-wrapper.jar` is there

Did I miss something?

2021-02-18 15:38 UTC, pgrzesik commented
Hm, that's very confusing. I was testing on `aws-java-gradle` and on `aws-groovy-gradle` and both of these don't have the wrapper included. I'm able to reproduce it locally and also hit the same on CI when testing out running tests against `npm pack`.

2021-02-18 15:50 UTC, pgrzesik commented
Looks like for three of the templates, `aws-clojure-gradle`, `aws-clojurescript-gradle` and `aws-kotlin-nodejs-gradle` it's properly included, but not for the rest of them - I didn't spot an obvious mistake yet but I'll keep digging, thanks for spotting that.

2021-02-19 08:12 UTC, pgrzesik commented
Thanks for the help with this one @medikoo :bow:

2021-02-19 09:30 UTC, medikoo approved these changes
Thank you @pgrzesik ! Great you've noticed that issue

2021-02-19 10:14 UTC, merged