refactor: Remove Bluebird from `lib/plugins/plugin`
serverless/serverless pull request #8984
Opened 2021-02-22 23:49 UTC by juanjoDiaz

Addresses: #7171

I'll keep them coming

2021-02-23 10:24 UTC, pgrzesik requested changes
Thank you @juanjoDiaz :bow: It looks good overall, I only have a few minor comments, please let me know what do you think

2021-02-23 10:24 UTC, pgrzesik commented on lib/plugins/plugin/install.js
> +    const message = [
I know it's not strictly part of `BbPromise` refactoring, but while we're at it - could you also simplify construction of that message? I don't think we need `join` here and putting it all in one line should be okay.

2021-02-23 10:24 UTC, pgrzesik commented on lib/plugins/plugin/install.js
> +    const message = [
I know it's not strictly part of `BbPromise` refactoring, but while we're at it - could you also simplify construction of that message? I don't think we need `join` here and putting it all in one line should be okay.

2021-02-23 10:24 UTC, pgrzesik commented on lib/plugins/plugin/install.js
> +    await this.validate();
does it have to be awaited? I believe it does not return a Promise after your changes in `utils.js`

2021-02-23 10:24 UTC, pgrzesik commented on test/unit/lib/plugins/plugin/install.test.js
> +      installStub = sinon.stub(pluginInstall, 'install').returns(Promise.resolve());
can we replace it with `.resolves` instead of `returns(Promise.resolve())`? It is repeated in a few other places as well

2021-02-23 17:24 UTC, juanjoDiaz commented
Done!

2021-02-24 09:38 UTC, pgrzesik requested changes
thank you @juanjoDiaz :bow: I believe there's one comment that wasn't addressed - it's a minor thing and after that we should be good to go :100:

2021-02-24 09:38 UTC, pgrzesik commented on lib/plugins/plugin/install.js
> +    await this.validate();
I think this wasn't addressed

2021-02-25 07:46 UTC, pgrzesik approved these changes
Thank you @juanjoDiaz, looks great :raised_hands:

2021-02-25 07:46 UTC, merged