refactor: Remove Bluebird from `lib/plugins/create`
serverless/serverless pull request #8996
Opened 2021-02-24 19:00 UTC by juanjoDiaz

Addresses: #7171

2021-02-25 08:01 UTC, pgrzesik requested changes
Thank you @juanjoDiaz - great work. I've added only a few comments, please let me know what do you think and after minor adjustments we should be ready to wrap this one up :100:

2021-02-25 08:01 UTC, pgrzesik commented on test/unit/lib/plugins/create/create.test.js
> +const { ServerlessError } = require('../../../../../lib/classes/Error');
let's import from `lib/serverless-error` instead of `lib/classes/Error` - `Error` module is going to be deprecated at some point in the future

2021-02-25 19:51 UTC, juanjoDiaz commented
Good feedback!

Done :)

2021-02-26 08:01 UTC, pgrzesik approved these changes
Awesome work @juanjoDiaz :partying_face: Thank you so much for pushing `Bluebird` refactoring at such great pace :bow:

2021-02-26 08:02 UTC, merged