show deprecation warning when unapplicable settings
serverless/serverless pull request #9238
Opened 2021-04-03 13:26 UTC by jkklapp

Closes: #9139

2021-04-06 11:00 UTC, pgrzesik requested changes
Thank you @jkklapp - that's a good start - please see my comments and let me know what do you think :bow:

2021-04-06 18:47 UTC, jkklapp commented on lib/plugins/aws/package/compile/events/apiGateway/lib/hack/updateStage.js
> +          if (this.apiGatewayRestApiId) {
@pgrzesik just to double check on the last line

> It should check for existence of provider.apiGateway.restApiId property in conjunction with the other two settings.

Is this deprecation to be logged when **both** tracing and logs are configured or is it one or the other too?

2021-04-06 18:51 UTC, jkklapp commented on docs/deprecations.md
> +When `provider.tracing.apiGateway` or `provider.logs.restApi` are set along with `provider.apiGateway.restApiId`, these are ignored when the API Gateway is created without a stack.
How about

```md
When `provider.apiGateway.restApiId` is set along `provider.tracing.apiGateway` or `provider.logs.restApi` these options are ignored as the API Gateway service has been created outside of serverless.
```
?

2021-04-07 08:10 UTC, pgrzesik requested changes
Thanks @jkklapp - I have a few minor comments, please let me know what do you think :bow:

2021-04-07 08:10 UTC, pgrzesik commented on docs/providers/aws/events/apigateway.md
> +The log streams will be generated in a dedicated log group which follows the naming schema `/aws/api-gateway/{service}-{stage}`. Note the property `restApi` can only be true if the API Gateway servic
Let's go with more descriptive documentation as the current proposal is vague. Let's start on a new line and go with something like:

```
**Note:** If external API Gateway resource is used and imported via `provider.apiGateway.restApiId` setting, `provider.logs.restApi` setting will be ignored.
```

2021-04-07 08:10 UTC, pgrzesik commented on docs/deprecations.md
> +
Let's go with something like:

```
When external API Gateway resource is used an imported via `provider.apiGateway.restApiId` setting, both `provider.logs.restApi` and `provider.tracing.apiGateway` will be ignored. These settings are applicable only if API Gateway resource is provisioned by Serverless Framework.
```

2021-04-07 08:10 UTC, pgrzesik commented on lib/plugins/aws/package/compile/events/apiGateway/index.js
> +            'Property "provider.tracing.apiGateway" is configured and is' +
Let's be more precise with this message and go with something like:

```
When external API Gateway resource is imported via `provider.apiGateway.restApiId`, property "provider.tracing.apiGateway" will be ignored.
```

2021-04-07 08:10 UTC, pgrzesik commented on lib/plugins/aws/package/compile/events/apiGateway/index.js
> +            'Property "provider.logs.restApi" is configured and is not ' +
Let's go with similar wording as the one proposed for `tracing` deprecation

2021-04-07 18:04 UTC, jkklapp commented on test/unit/lib/plugins/aws/package/compile/events/apiGateway/index.test.js
> +      tracing: { apiGateway: true },
I was trying to make tests cover the new code, I'll revert the change

2021-04-08 08:58 UTC, pgrzesik requested changes
Thank you @jkklapp - I believe a few comments from previous review weren't addressed - could you please check them out again and let me know if I missed something?

2021-04-08 08:58 UTC, pgrzesik commented on lib/plugins/aws/package/compile/events/apiGateway/index.js
> +            'Property "provider.tracing.apiGateway" is configured and is' +
Looks like this wasn't addressed, am I correct?

2021-04-08 08:58 UTC, pgrzesik commented on lib/plugins/aws/package/compile/events/apiGateway/index.js
> +            'Property "provider.logs.restApi" is configured and is not ' +
Same here

2021-04-08 08:58 UTC, pgrzesik commented on docs/providers/aws/events/apigateway.md
> +The log streams will be generated in a dedicated log group which follows the naming schema `/aws/api-gateway/{service}-{stage}`. **Note:** If external API Gateway resource is used and imported via `p
Looks good - let's put **Note:** on a separate line

2021-04-18 08:56 UTC, pgrzesik requested changes
Thank you @jkklapp - looks good overall, I missed one minor thing and after that we should be good to go :100: 

Note: After pushing new changes, please request a review, otherwise it's hard to know if the changes are ready for a review.

2021-04-18 08:56 UTC, pgrzesik commented on docs/deprecations.md
> +<a name="AWS_API_GATEWAY_NON_APPLICABLE_SETTINGS"><div>&nbsp;</div></a>
Sorry for not noticing it before - it should be listed as first on the list, right after `How to disable specific deprecation logs` section

2021-04-18 15:53 UTC, jkklapp commented
@pgrzesik I moved the message in `deprecations.md` please confirm this is ok.

2021-04-19 07:39 UTC, pgrzesik approved these changes
Thank you @jkklapp :bow: Looks great :+1:

2021-04-19 07:40 UTC, merged