refactor: Use `async/await` in `analytics`
serverless/serverless pull request #9267
Opened 2021-04-08 16:06 UTC by pgrzesik

Finishes 1. of `Local` 

Addresses: #9257

2021-04-09 12:01 UTC, medikoo requested changes
@pgrzesik looks very good! I've just noticed that `try/catch` spans are in most cases wider than in non async/await logic, which may result with some important issues being hidden from us in a future.

I've commented on those bits

2021-04-09 12:01 UTC, medikoo commented on lib/utils/analytics/index.js
> +  return null;
This `return` originally was intended to supress array result from `Promise.all` and here it's moved, and no longer applied in same logic point.

2021-04-09 15:43 UTC, medikoo approved these changes
Looks great :+1

I've suggested two more style improvements, but they're just style nits

2021-04-09 15:43 UTC, medikoo commented on lib/utils/analytics/index.js
> +    --ongoingRequestsCount;
To not have it repeated, this could be in `finally`

2021-04-09 15:43 UTC, medikoo commented on lib/utils/analytics/index.js
> +    return null;
We may just `return` (no need to `return null`, same below. In old version it was `null`, to visually better signal intent (`then(() => {}` or `then(() => { return undefined }` is either confusing or dirty)

2021-04-12 15:51 UTC, medikoo submitted a review, later dismissed
Looks great 👍

2021-04-13 07:15 UTC, pgrzesik commented
Pushed again only due to snyk check hanging - no changes were introduced from last review

2021-04-13 07:15 UTC, merged