feat: add ${merge(...)} pseudo-variable support
serverless/serverless pull request #9314
Opened 2021-04-17 20:15 UTC by glb

Introduces a `merge` variable source, so a single object or array can be constructed from multiple sources as follows:

```yml
custom:
  environment:
    FOO: value

provider:
  environment: ${merge(${self:custom.environment}, ${file(common-env.json)}})}
```

Important constraints met:
* Supports constructing plain objects and arrays exclusively
* Imply a top level merge. In plain object case it should work similarly to `Object.assign({}, param1, param2, ..)`. In case of arrays: `[].push(...param1, ...param2)`
* In case of plain object construction throw an exception if two input objects share same key (does not silently override them)
* Ensure that all input params are either exclusively plain objects, or exclusively arrays (throw otherwise)

Addresses: #8037 

Related: serverless/utils#79, #9299.

2021-04-19 12:09 UTC, medikoo requested changes
@glb that looks great! I'm really glad we will finally have this in. I've suggested just few very minor improvement (sorry for nitpicking), and we should be good to go!

2021-04-19 12:09 UTC, medikoo commented on docs/providers/aws/guide/variables.md
> +- [Merge pseudo-variable](#merge-pseudo-variable)
Let's name it: _Merge multiple object/array sources_ ("Pseudo variable" term is used with some AWS variables, but we don't use this term for Serverless Variables)

2021-04-19 12:09 UTC, medikoo commented on lib/configuration/variables/sources/merge.js
> +    if (!Array.isArray(params) || params.length < 2) {
Let's simplify check to `!params || params.length < 2` (`params` if exists is guaranteed to be an array)

2021-04-19 12:09 UTC, medikoo commented on lib/configuration/variables/sources/merge.js
> +        }, []),
Let's maybe use normal iteration instead (using `reduce` feels controversial, as it's not a real use case for reduce)

I'd put it as:

```javascript
const result = [];
for (const param of params) result.push(...param)
return { value: result };
```

2021-04-19 12:09 UTC, medikoo commented on lib/configuration/variables/sources/merge.js
> +    if (params.every((item) => typeof item === 'object' && !Array.isArray(item))) {
Let's use `type/plain-object/is`  to confirm on an item.

2021-04-19 12:09 UTC, medikoo commented on lib/configuration/variables/sources/merge.js
> +      return { value: Object.assign({}, ...params), isPending: false };
We can remove `isPending: false` (that's default)

2021-04-24 23:48 UTC, glb commented
@medikoo I've updated as requested.

2021-04-26 08:04 UTC, medikoo requested changes
@glb that looks great! I've just proposed some changes to error messaging, so it matches conventions found in other sources. Also now we require all `ServelressError` instances to be accompanied with a code. I proposed a values for each error

Thank you!

2021-04-26 08:04 UTC, medikoo commented on lib/configuration/variables/sources/merge.js
> +              `duplicate key \`${key}\` in \${merge(...)}[${index}]; first seen in \${merge(...)}[${keys[key]}]`
Let's reword to ``Unsafe arguments for variable "merge" source: Duplicate key "${key}" in [${index}] (first seen in [${keys[key]}])``, and add code `UNSAFE_VARIABLE_MERGE_PARAMS`

2021-04-26 08:04 UTC, medikoo commented on lib/configuration/variables/sources/merge.js
> +    throw new ServerlessError('${merge(...)} needs a list of arrays or objects to merge');
Let's reword to `Invalid arguments for variable "merge" (expected exclusive list of arrays or plain objects)` and add code `INVALID_VARIABLE_MERGE_PARAMS`

2022-10-21 16:58 UTC, glb commented
Aging this out. I doubt I'll be able to get back to it. Thanks for the patient conversation!

2022-10-21 16:58 UTC, closed without merging