Add support for more S3 URI formats
serverless/serverless pull request #9411
Opened 2021-04-30 20:18 UTC by zachwhaley

#9380 Added support for most S3 bucket URIs, but not ones with region in their format, e.g. any bucket outside of us-east-1.

Closes: #9403

2021-04-30 20:36 UTC, bishtawi commented on lib/plugins/aws/utils/parse-s3-uri.js
> +  new RegExp('^s3://(?<bucket>[^/]+)/(?<key>.+)'),
I didnt realize you could label your matches. That is really cool.

2021-04-30 20:42 UTC, bishtawi commented on lib/plugins/aws/utils/parse-s3-uri.js
> +  new RegExp('s3(\\.[\\w\\d-]+)?\\.amazonaws\\.com/(?<bucket>[^/]+)/(?<key>.+)'),
For this regex and the one above, you should probably support urls with dashes separating the `s3` from the `region` as apparently `s3-region` is a valid url is some aws regions.

Ex: `https://my-bucket.s3-us-west-2.amazonaws.com`

So `s3([.-][\\w\\d-]+)?`.

2021-05-03 08:08 UTC, pgrzesik requested changes
Thank you @zachwhaley - it looks great :raised_hands: Before we merge, it looks like there are minor issues with formatting - could you please take a look at it? After that we should be good to go :rocket:

2021-05-09 19:20 UTC, pgrzesik approved these changes
Thank you @zachwhaley, looks great :+1:

2021-05-09 19:21 UTC, merged