api gateway method depends on permission
serverless/serverless pull request #9609
Opened 2021-06-16 12:17 UTC by nyamba

this is for https://github.com/serverless/serverless/issues/9525

Closes: #{9525}

2021-06-17 12:37 UTC, pgrzesik requested changes
Thanks a lot @nyamba, it looks good :+1: It would be, however, great to ensure that this functionality is covered by tests. The tests should land here: https://github.com/serverless/serverless/blob/master/test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js and should use `runServerless`

2021-06-17 12:37 UTC, pgrzesik commented on lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.js
> +      const apiGetwayPermission = this.provider.naming.getLambdaApiGatewayPermissionLogicalId(
there's a small typo - `apiGetway` should be `apiGateway`

2021-06-21 07:11 UTC, nyamba commented
Thanks @pgrzesik, pushed the improvements ;-)

2021-06-21 15:34 UTC, pgrzesik requested changes
Thanks @nyamba - looks good overall, I only have small suggestions, please let me know what do you think :bow:

2021-06-21 15:34 UTC, pgrzesik commented on test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
> +  it('should depends on permission resource', async () => {
Let's move it to this `describe`:
```
describe('#compileMethods v2()', () => {
```

as it's indended to capture all new tests written with `runServerless` approach

2021-06-21 15:34 UTC, pgrzesik commented on test/unit/lib/plugins/aws/package/compile/events/apiGateway/lib/method/index.test.js
> +      configExt: {
Do we need that configuration extension? The `apiGateway` fixture already configures some events that I believe we can use in this test

2021-06-25 07:45 UTC, nyamba commented
please check, @pgrzesik

2021-06-25 08:18 UTC, pgrzesik approved these changes
Great changes, thank you @nyamba :bow:

2021-06-25 08:20 UTC, merged