Fix IAM documentation
serverless/serverless pull request #9735
Opened 2021-07-13 09:43 UTC by mnapoli

I think I noticed some mistakes in the IAM documentation (`,` at the end of some lines, which AFAICT is incorrect in YAML).

2021-07-13 09:44 UTC, mnapoli commented on docs/providers/aws/guide/iam.md
> +          Action: 'iam:DeleteUser'
Note: I've also changed `NotAction` -> `Action`, this is a much more familiar and common use case.

`NotAction` can be confusing, and an easy typo to make when copy-pasting the example from the docs. For example myself I copy-pasted the example and later realized that it was `NotAction` (also first time I see this).

2021-07-13 10:42 UTC, pgrzesik requested changes
thanks a lot @mnapoli - great catch. There's one minor thing which is failing check for commit message - we're using `commitlint` to validate it - in this case proper commit message could be for example `docs(AWS IAM): Fix invalid example` or something along those lines

2021-07-14 10:23 UTC, pgrzesik approved these changes
I'm going to merge this one and adjust the commit message :+1: Thanks once again @mnapoli :bow:

2021-07-14 10:23 UTC, merged

2021-07-15 10:49 UTC, mnapoli commented
Ah thank you @pgrzesik!