feat: add new artifactsVersioningMode option with 'hash' capability
serverless/serverless pull request #9828
Opened 2021-08-11 13:46 UTC by remi00

Addresses: #8666 

**Overview**:

 - Add `artifactsVersioningMode` with support for `hash` value that switches the way how artifacts` S3 keys are generated during **package** and **deploy** commands
 - Change upload functionality to precede any `S3.upload` with `S3.headObject` which allows to avoid re-uploading of already uploaded artifacts
 - Extract the timestamp value used for upload paths from the artifactsDirectoryName so that it is easier to perform names generation
 - Update unit tests according to changed implementation

_In general, following a technical solution proposal described within #8666_

**More changes to come in upcoming PRs:**

- Support for rollback and s3 bucket cleanup
- Add deprecation notice for not using the new mode
- Docs update to tell about artifactsVersioningMode and how to make the use of it in the workflow

2021-08-17 13:46 UTC, medikoo requested changes
@remi00 that looks very very promising!

Indeed it shows that we can probably pursue that improvement without any breaking changes (and extra mode switches) involved, and that's a significant for us.

However, as it it touches a very sensitive part of a Framework, I propose so we divide this work a bit:
1. First let's create a PR that converts to native promises and async/await any functions that have to be updated to deliver this optimization.
2. Let's resign from refactors which are not needed. Touching those parts increases risk for bugs and introducing incompatibility with plugins. So if there's no strong reason, let's not change how method works, let's not rename them etc.
3. Having above addressed let's keep this PR as minimal mandatory set of changes to have that optimization in

What do you think?

2021-08-18 13:07 UTC, mnapoli commented
Hi 👋 On the non-technical side, before merging, I'd love to clarify all the changes that will impact users. That could be: new YAML fields, deprecations, performances changes, etc.

I've tried to follow this PR as well as #8666 but a lot was discussed, and it's focused on implementation discussions. Could we add a "user impact" recap, either in this PR or #8666?

@medikoo if this PR is exactly based on your proposal in #8666 then maybe you could add that to #8666? If this PR is diverging from #8666, then maybe @remi00 you could add that to your PR?

2021-08-18 13:14 UTC, medikoo commented
> @medikoo if this PR is exactly based on your proposal in #8666 then maybe you could add that to #8666? If this PR is diverging from #8666, then maybe @remi00 you could add that to your PR?

@mnapoli Changes this PR proposes can be applied transparently without a need for any deprecation or extra flag.
My initial spec (as currently described in https://github.com/serverless/serverless/issues/8666) proposed different, more invasive scenario. Still I think approach as taken here by @remi00 can really work, and if it's going to be confirmed, it's definitely way better approach. I see just one potential (but rather edge case) issue. I'll update the #8666 description later today or tomorrow to reflect that

2021-08-18 13:45 UTC, mnapoli commented
Cool, so the only impact is the deployment speed, right? The new deployment system will immediately apply to every user, correct?

Regarding deployment speed, AFAICT we have that info:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/720328/129908572-6e8e6b77-4108-4c94-bf0f-875f529eb6b2.png">

Is it still relevant? Sounds like a win in that kind of scenario, as total deployment time goes from 14 minutes to 6 minutes in case of changes only relevant to a few Lambda functions.

What would be the performance change when deploying changes of all Lambda functions?

Similarly, what would be the deploy performance change for applications with only 1 (or 2) Lambdas?

And finally: is the patch only changing performance for services when functions are packaged separately? Or does it also change things for services where functions are all packaged together?

2021-08-18 14:02 UTC, medikoo commented
> Cool, so the only impact is the deployment speed, right?

@mnapoli Yes, currently our design is broken, as on consecutive deployments we always attempt to re-upload assets that we already have uploaded with previous deployments.

It feels obvious that in kind of services where there's a lot KB to upload, or where network is slow we can drive observable improvements if we stop uploading content that's already there. 

> The new deployment system will immediately apply to every user, correct?

Yes

> Sounds like a win in that kind of scenario, 

What @remi00 posted, is just an example (aka POC) which proves that this optimization will bring noticeable improvement in this kind of a service

> What would be the performance change when deploying changes of all Lambda functions?
> What would be the deploy performance change for applications with only 1 (or 2) Lambdas?

If there would be no changes to their artifacts the difference will depend on artifact size and network reliability. If artifacts for those lambdas have changed there will be no difference.

>  And finally: is the patch only changing performance for services when functions are packaged separately?

No, it's a general improvement that affects all zip artifacts we upload, and packaging method here is irrelevant

2021-08-19 09:03 UTC, pgrzesik reviewed
Thanks @remi00, I've also went over the changes and I generally agree with suggestions from @medikoo. I have one question though, how do you plan to address the bucket cleanup functionality with this implementation? After deployment, by default, we only keep artifacts from 5 previous deploys and that's a subject to user's recofniguration. Unless I'm missing something, this PoC does not include changes to that logic.

2021-08-24 10:01 UTC, remi00 commented
I decided to create a new PR #9876, so closing this one.

2021-08-24 10:01 UTC, closed without merging