fix(AWS HTTP API): Handle catch-all shadowing route (#9840)
serverless/serverless pull request #9863
Opened 2021-08-19 19:32 UTC by kazkansouh

Closes: #9840

---

Removes couple checks to allows for configs such as the following:

```yaml
functions:
  handler:
    handler: handler.handler
    events:
      - httpApi: OPTIONS /a
      - httpApi: ANY /a
```

That is, catch-all's that shadow other routes with same paths are allowed.

2021-08-19 21:01 UTC, pgrzesik requested changes
Thank you @kazkansouh :bow: I've tested it locally and it works great :100: I only have one concern, let me know what do you think and we'll be good to go

2021-08-20 07:07 UTC, kazkansouh commented on lib/plugins/aws/package/compile/events/httpApi.js
> -              for (const allowedMethod of allowedMethods) {
@pgrzesik you are correct - Ill refactor to make it conservative. I saw an easy win for making the code cleaner but did not consider redeployment.

2021-08-20 07:44 UTC, kazkansouh commented on lib/plugins/aws/package/compile/events/httpApi.js
> -              for (const allowedMethod of allowedMethods) {
Ok, I've pushed a new version :smile: 

I'm thinking that there is no real advantage of raising the above as a separate issue as listing all the methods or using a `*` is effectively the same. But if you would like to me open an issue so its recorded - just let me know.

2021-08-20 08:05 UTC, pgrzesik commented on lib/plugins/aws/package/compile/events/httpApi.js
> -              for (const allowedMethod of allowedMethods) {
I think it's such a minor thing that we don't need an issue for it and we should probably just keep it the way it is to not introduce potential need to redeploy for such a minor change

2021-08-20 08:21 UTC, kazkansouh commented on lib/plugins/aws/package/compile/events/httpApi.js
> -              for (const allowedMethod of allowedMethods) {
Ok, thanks :+1:

2021-08-20 08:26 UTC, pgrzesik approved these changes
Great job, thank you @kazkansouh :bow:

2021-08-20 08:27 UTC, merged