Introduce AWS provider s3 directory path variables
serverless/serverless pull request #9904
Opened 2021-09-01 11:49 UTC by remi00

**What it does?**

- Introduce AWS provider s3 directory path variables that will allow for proper directory structure within artifacts S3 bucket once hash artifacts versioning will be added

**What else is important?**

- Implements [this suggestion](https://github.com/serverless/serverless/pull/9876#discussion_r698418058) from PR #9876

2021-09-20 15:55 UTC, remi00 commented
Hello @medikoo could you please take a look? Do these changes make sense from your point of view?

2021-09-21 07:39 UTC, medikoo requested changes
Thank you @remi00 and sorry that it took us so long to review that (for some reason it got lost in a process, and it's great you've reminded us)

In general it looks very good, I have just few suggestions

2021-09-21 07:39 UTC, medikoo commented on lib/plugins/aws/provider.js
> +    provider.s3DeploymentDirectoryPath = `${prefix}/${serviceStage}/${dateString}`;
Let's not set it on `service.provider`, this object reflects user configuration and ideally if we do not mix it with internally resolved data (although I know that currently our internals in few places do that).

Ideally if `s3CodeArtifactsDirectoryPath` and `s3DeploymentDirectoryPath` getters simply resolve it on spot
And _timestamp_ part can be set on provider instance in its constructor as e.g. `this.deploymentTimestamp = ...`

2021-09-21 07:39 UTC, medikoo commented on lib/plugins/aws/provider.js
> +    provider.s3CodeArtifactsDirectoryPath = `${prefix}/${serviceStage}/code-artifacts`;
In context of this PR we should not yet introduce `s3CodeArtifactsDirectoryPath`

2021-09-21 07:39 UTC, medikoo commented on lib/plugins/aws/provider.js
> +  get s3CodeArtifactsDirectoryPath() {
In context of this PR we should not yet introduce `s3CodeArtifactsDirectoryPath`, as so far path is same as `s3DeploymentDirectoryPath`.

2021-09-21 07:39 UTC, medikoo commented on lib/plugins/aws/rollback.js
> +    service.provider.s3DeploymentDirectoryPath = `${prefix}/${dateString}`;
I think here what should be overriden is just `serverless.getProvider('aws').deploymentTimestamp` and having that getters should start resolve the right deployment path (?)

2021-09-21 07:39 UTC, medikoo commented on test/unit/lib/plugins/aws/provider.test.js
> +    it('should provide proper code artifacts S3 directory path', () => {
Any new tests should be based on [`runServerless`](https://github.com/serverless/test/blob/master/docs/run-serverless.md) util, e.g. see how `provider.getRegion()` is tested: https://github.com/serverless/serverless/blob/9e308bdf041c73eb2d27408ae4e03bc10fe9bf8a/test/unit/lib/plugins/aws/provider.test.js#L602-L637

2021-11-03 07:48 UTC, remi00 commented
@wwwehr you mentioned in #9876 there are some changes already in the baseline that handle this. Could you point me to them? Looks like it was not obvious to me yesterday evening. @medikoo maybe you know and can help?

2023-11-27 08:48 UTC, remi00 commented
This is already far away from possibility of merging to main

2023-11-27 08:48 UTC, closed without merging